name: 'Reusable Setup'
description: 'Install node, pnpm and local node packages'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@71c92474e7e4f5bca283fb17ef80fba9cdb2b4b1 # v6

    - name: Install Packages
      shell: bash
      run: pnpm install

    - name: Install Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version-file: 'package.json'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
