name: Reopened bug reports

on:
  issues:
    types: [reopened]

jobs:
  add-reopened-bugs-to-triage:
    if: contains(github.event.issue.labels.*.name, 'bug report')

    runs-on: ubuntu-latest

    steps:
      - name: add labels
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90 # renovate: tag=v1.0.4
        with:
          add-labels: "reopened"
          repo-token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
