name: "dev"

concurrency: "dev"

on:
  push:
    branches:
      - dev

jobs:
  code-scanning:
    uses: ./.github/workflows/reusable-codeql-analysis.yml

  toolbox-tests:
    uses: ./.github/workflows/reusable-toolbox-tests.yml

  toolbox-deploy:
    needs: 
      - toolbox-tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Build graphql-toolbox
        run: yarn build
        env:
          SEGMENT_GRAPHQL_TOOLBOX_PROD_SOURCE: ${{ secrets.SEGMENT_GRAPHQL_TOOLBOX_PROD_SOURCE }}
          CANNY_GRAPHQL_TOOLBOX_APP_ID: ${{ secrets.CANNY_GRAPHQL_TOOLBOX_APP_ID }}
      - uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83 # renovate: tag=v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-2"
          SOURCE_DIR: "dist" # optional: defaults to entire repository
