name: Issue labeled

on:
  issues:
    types: [labeled]

jobs:
  bug_report_label:
    if: ${{ github.event.label.name == 'bug report' }}

    runs-on: ubuntu-latest

    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Many thanks for raising this bug report @${{ github.event.issue.user.login }}. :bug: We will now attempt to reproduce the bug based on the steps you have provided.

            Please ensure that you've provided the necessary information for a minimal reproduction.
  confirmed_label:
    if: ${{ github.event.label.name == 'confirmed' }}

    runs-on: ubuntu-latest

    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            We've been able to confirm this bug using the steps to reproduce that you provided - many thanks @${{ github.event.issue.user.login }}! :pray: We will now prioritise the bug and address it appropriately.
