name: "Lint GitHub Actions"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    paths:
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: reviewdog/action-actionlint@053c5cf55eed0ced1367cdc5e658df41db3a0cce # v1.59.0
        with:
          reporter: github-check
          fail_on_error: true
