name: "Toolbox tests"

on:
  workflow_call:

jobs:
  ui-e2e-tests:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:5-enterprise
        env:
          NEO4J_AUTH: neo4j/password
          NEO4J_PLUGINS: '["apoc"]'
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
        ports:
          - 7687:7687

    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run @neo4j/graphql-toolbox unit tests
        run: yarn test:unit
      - name: Run @neo4j/graphql-toolbox e2e tests
        run: yarn test
        env:
          NEO_USER: neo4j
          NEO_PASSWORD: password
          NEO_URL: bolt://localhost:7687
      - name: Upload playwright report on failure
        if: failure()
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: playwright-test-failure-report
          path: tests/artifacts
          retention-days: 4
