name: "Toolbox Build"

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "src/**"

jobs:
  build-graphql-toolbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Build the Toolbox
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          yarn build
          echo "$PULL_REQUEST_NUMBER" > ./dist/prnumber
      - name: Archive Toolbox build
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: graphqltoolbox
          path: dist
