name: "Toolbox Build"

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "src/**"

jobs:
  build-graphql-toolbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Build the Toolbox
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          yarn build
          echo "$PULL_REQUEST_NUMBER" > ./dist/prnumber
      - name: Archive Toolbox build
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: graphqltoolbox
          path: dist
