name: "Toolbox Teardown"

on:
  pull_request_target:
    paths:
      - "src/**"
    types:
      - closed

jobs:
  teardown-graphql-toolbox:
    runs-on: ubuntu-latest

    steps:
      - uses: ./github/actions/reusable-setup
        with:
          install-packages: 'false'

      - name: Teardown graphql-toolbox
        run: |
          npm install -g surge
          surge teardown neo4j-graphql-toolbox-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        with:
          header: toolbox
          message: |
            Thanks for the Neo4j GraphQL Toolbox updates.

            The Neo4j GraphQL Toolbox has now been torn down - reopening this PR will republish it.
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
