name: "Toolbox Build"

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "src/**"

jobs:
  build-graphql-toolbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Build the Toolbox
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          yarn build
          echo "$PULL_REQUEST_NUMBER" > ./dist/prnumber
      - name: Archive Toolbox build
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: graphqltoolbox
          path: dist
