name: "Toolbox Build"

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "src/**"

jobs:
  build-graphql-toolbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - uses: ./.github/actions/reusable-setup/

      - name: Build the Toolbox
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          pnpm build
          echo "$PULL_REQUEST_NUMBER" > ./dist/prnumber

      - name: Archive Toolbox build
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: graphqltoolbox
          path: dist
